rancher-status-lb:
  scale: 1
  image: rancher/load-balancer-service
  ports:
  - 20040:8889
  tty: true
  links:
  - rancher-status
  stdin_open: true
  labels:
    io.rancher.container.dns: "true"
    io.rancher.stack.name: "rancher-status-load-balancer"
    io.rancher.container.hostname_override: "rancher-status-load-balancer"
    io.rancher.scheduler.global: "true"
  health_check:
    port: 42
    interval: 300
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 50
rancher-status:
  image: srflaxu40/rancher_status_page:${DOCKER_TAG}
  labels:
    io.rancher.container.dns: "true"
    io.rancher.stack.name: "srflaxu40/rancher_status_page:${DOCKER_TAG}"
    io.rancher.container.hostname_override: "rancher-status-page"
    io.rancher.scheduler.global: "true"
    io.rancher.container.network: "true"
  stdin_open: true
  tty: true
  health_check:
    port: 8889
    interval: 300
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 50
  environment:
    - DOCKER_TAG=${DOCKER_TAG}
